var common = {
  headers: [
    {
      text: 'nick',
      align: 'start',
      sortable: true,
      value: 'nick',
    },
    { text: 'tier', value: 'tier' },
    { text: 'top', value: 'top' },
    { text: 'jg', value: 'jg' },
    { text: 'mid', value: 'mid' },
    { text: 'ad', value: 'ad' },
    { text: 'sup', value: 'sup' },
    { text: 'score', value: 'score' },
    { text: 'remark', value: 'remark' },
  ],
  member: [
    {
      nick: '대봉동왕주먹',
      tier: 'B',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: false,
      score: '',
      remark: '세주아니원챔',
    },
    {
      nick: '한은총재',
      tier: 'B',
      top: true,
      jg: false,
      mid: true,
      ad: false,
      sup: true,
      score: '',
      remark: '칼바람 9천판',
    },
    {
      nick: '외계인해라',
      tier: 'B',
      top: false,
      jg: true,
      mid: false,
      ad: false,
      sup: false,
      score: '',
      remark: '녹턴원챔으로 진화중',
    },
    {
      nick: '아름다운미하',
      tier: 'S',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: false,
      score: '',
      remark: '야스오원챔',
    },
    {
      nick: '평타피하는중',
      tier: 'S',
      top: false,
      jg: false,
      mid: false,
      ad: true,
      sup: false,
      score: '',
      remark: '골드출신 원딜러',
    },
    {
      nick: '전공암살자',
      tier: 'S',
      top: false,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '',
      remark: '브랜드서폿원챔',
    },
    {
      nick: '워웍 킴',
      tier: 'S',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: false,
      score: '',
      remark: '워웍 탑워황 원챔',
    },
    {
      nick: '수학의 경석',
      tier: 'S',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: false,
      score: '',
      remark: '탑탱커의 정석',
    },
    {
      nick: '헤스먼달프',
      tier: 'G',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '',
      remark: '게맘, 갑각류 러버, 최근엔 새우까지추가 ,최근 골드달성',
    },
    {
      nick: '김깨도리',
      tier: 'G',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '',
      remark: '세트/세주 투챔',
    },
    {
      nick: '벤트탓옹',
      tier: 'G',
      top: false,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '',
      remark: '롤체 M',
    },
    {
      nick: 'EKAPE',
      tier: 'G',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: true,
      score: '',
      remark: '나밟꿈의 실수로 그의 명칭이 탈출... 나밟꿈 라인전 개패듯이 팸',
    },
    {
      nick: '언덕위의 포뇨',
      tier: 'G',
      top: false,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '',
      remark: '포뇨 : 게임은 스킨을 위해 하는 것이다.',
    },
    {
      nick: '박새싹',
      tier: 'G',
      top: false,
      jg: false,
      mid: false,
      ad: true,
      sup: false,
      score: '',
      remark: '플레출신',
    },
    {
      nick: '진짜 섭섭한탑',
      tier: 'G',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: false,
      score: '',
      remark: '너무나 섭섭해',
    },
    {
      nick: 'cast',
      tier: 'G',
      top: false,
      jg: false,
      mid: false,
      ad: true,
      sup: false,
      score: '',
      remark: '왕자님',
    },
    {
      nick: '순줌',
      tier: 'G',
      top: false,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '5',
      remark: '음식 피셜 플1서폿',
    },
    {
      nick: '안오면박아야지뭐',
      tier: 'G',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: false,
      score: '중중',
      remark: '사이드는 묵직하게',
    },
    {
      nick: '코루스폴',
      tier: 'G',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: false,
      score: '4',
      remark: '경찰아찌, 프로포폴(총재님 지어주심)',
    },
    {
      nick: '솜포도',
      tier: 'G',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: false,
      score: '3',
      remark: '개억까당하는중',
    },
    {
      nick: 'LjYoon2',
      tier: 'G',
      top: false,
      jg: true,
      mid: false,
      ad: false,
      sup: false,
      score: '4',
      remark: '워웍 그자체 정글 워황 , 샤코 투챔',
    },
    {
      nick: '간장쥬스',
      tier: 'G',
      top: false,
      jg: false,
      mid: true,
      ad: false,
      sup: false,
      score: '',
      remark: '애니비아원챔',
    },
    {
      nick: '4등 못하면',
      tier: 'G',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: false,
      score: '',
      remark: '',
    },
    {
      nick: '꽃승아',
      tier: 'G',
      top: false,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '3',
      remark: '유부초밥드립에 뿜음, 플레4서폿유저 출신',
    },
    {
      nick: '말랑말캉해',
      tier: 'G',
      top: true,
      jg: true,
      mid: false,
      ad: true,
      sup: false,
      score: '',
      remark: '',
    },
    {
      nick: '나밟꿈',
      tier: 'P',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: true,
      score: '4',
      remark: 'me',
    },
    {
      nick: '엔비코',
      tier: 'P',
      top: false,
      jg: true,
      mid: false,
      ad: false,
      sup: false,
      score: '중중',
      remark: '솔랭정신, 녹턴원챔, 자칭 캐리머신, 강타 잘못 씀,여채정 제자',
    },
    {
      nick: '곰지영',
      tier: 'P',
      top: false,
      jg: false,
      mid: false,
      ad: true,
      sup: true,
      score: '',
      remark: '월루,엑셀장인, 자칭유미원챔, 다른챔 잘다루는거 봤음',
    },
    {
      nick: '문고리만우리집',
      tier: 'B',
      top: false,
      jg: true,
      mid: true,
      ad: false,
      sup: false,
      score: '중하',
      remark: '문고리도우리집(수성못), 애니비아 원챔급의 픽률',
    },
    {
      nick: '니읏',
      tier: 'P',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: true,
      score: '',
      remark: 'bhc',
    },
    {
      nick: '꽃방울니코',
      tier: 'P',
      top: false,
      jg: true,
      mid: true,
      ad: false,
      sup: false,
      score: '5',
      remark: '다이아1 출신 그냥 모든겜 고수',
    },
    {
      nick: '누우우누',
      tier: 'P',
      top: false,
      jg: false,
      mid: true,
      ad: true,
      sup: true,
      score: '3',
      remark: '강철멘탈',
    },
    {
      nick: '피야',
      tier: 'P',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: true,
      score: '4',
      remark: '서폿 골드 원딜미드 다4',
    },
    {
      nick: '너구리맘',
      tier: 'D',
      top: true,
      jg: false,
      mid: false,
      ad: true,
      sup: false,
      score: '5',
      remark: '당신 카밀 아트는 벤이야!',
    },
    {
      nick: '혀나님',
      tier: 'D',
      top: false,
      jg: false,
      mid: true,
      ad: false,
      sup: false,
      score: '',
      remark: '우리방 방장, 재간둥이 장인 ,본인은 P라주장 자랭 M',
    },
    {
      nick: '여채정',
      tier: 'D',
      top: false,
      jg: true,
      mid: false,
      ad: false,
      sup: false,
      score: '6',
      remark: '응애장인, 자칭 이렐장인, 정글은 진짜 장인;;',
    },
    {
      nick: '수성못',
      tier: 'D',
      top: false,
      jg: false,
      mid: true,
      ad: false,
      sup: false,
      score: '5',
      remark: '롤도 잘하고 현실도 챌린저인 이런 불공평한 세상!',
    },
    {
      nick: '티모야힘내',
      tier: 'D',
      top: false,
      jg: false,
      mid: false,
      ad: true,
      sup: false,
      score: '4',
      remark: '원딜러인데 티모야 힘내...?',
    },
    {
      nick: '사미랴',
      tier: 'D',
      top: false,
      jg: false,
      mid: false,
      ad: true,
      sup: false,
      score: '5',
      remark: '닉 = 장인',
    },
    {
      nick: 'PAKA편집자',
      tier: 'D',
      top: false,
      jg: true,
      mid: false,
      ad: false,
      sup: false,
      score: '4',
      remark: '롤체D, 샤코원챔',
    },
    {
      nick: '광개토익왕',
      tier: 'D',
      top: false,
      jg: true,
      mid: false,
      ad: false,
      sup: false,
      score: '5',
      remark: '토익장인 ,킨드원챔',
    },
    {
      nick: '머스탱',
      tier: 'D',
      top: false,
      jg: false,
      mid: true,
      ad: false,
      sup: false,
      score: '5',
      remark: '미드럼블 원챔 따른 챔프잡을시 S~G사이 추정',
    },
    {
      nick: '케이윌 꽃이핀다',
      tier: 'D',
      top: true,
      jg: true,
      mid: true,
      ad: true,
      sup: true,
      score: '6',
      remark: '뚝배기 장인',
    },
    {
      nick: '탑꾀돌이',
      tier: 'D',
      top: true,
      jg: false,
      mid: false,
      ad: false,
      sup: false,
      score: '5',
      remark: '항상 캐리를 외치시는 진정한 탑솔러, 노익장',
    },
    {
      nick: '음 식',
      tier: 'M',
      top: false,
      jg: false,
      mid: false,
      ad: false,
      sup: true,
      score: '6',
      remark: '음 식 , 상병 신음식',
    },
  ],
  warResult: {
    data: [
      {
        date: '2020-10-03',
        result: '2승 0패 A팀 승리',
        teamA: {
          first: [
            '나밟꿈,오른,2/2/9, 32킬중 11킬관여',
            '무한도전난공불락,올라프,11/3/7',
            '죽돌이필, 직스, 13/1/5 ',
            '티모야힘내,이즈리얼,4/3/8',
            '꽃승아,유미,2/1/15',
          ],
          second: [
            '나밟꿈,문도박사,8/4/18,45킬중 26킬관여',
            '무한도전난공불락,리신,11/7/17',
            '한은총재,오리아나,14/7/19',
            '티모야힘내,루시안,5/11/18',
            '꽃승아,아무무,7/15/18',
          ],
          third: [
            '나밟꿈,쉔,2/4/16,33킬 중 18킬관여',
            '무한도전난공불락,비에고,15/6/7',
            '한은총재,오리아나,4/6/16',
            '티모야힘내,이즈리얼,9/3/15',
            '꽃승아,유미,3/2/23',
          ],
        },

        teamB: {
          first: [
            '뉴꾀돌이,릴리아,4/6/3 10킬 중 7킬관여',
            '엔비코,볼리베어,3/8/3',
            '한은총재,오리아나,0/5/2',
            '머스탱,미스포춘,1/7/4',
            '음식,레오나,2/6/3',
          ],
          second: [
            '뉴꾀돌이,세트,12/8/10,44킬 중 22킬관여',
            '엔비코,세주아니,6/12/23',
            '죽돌이필,말자하,7/7/14',
            '머스탱,카이사,16/10/12',
            '음식,쓰레쉬,3/8/32',
          ],
          third: [
            '뉴꾀돌이,아트록스,6/8/3,21킬중 9킬 관여',
            '엔비코,다이애나,6/6/10',
            '죽돌이필,럭스,2/8/9',
            '머스탱,진,/6/4/5',
            '음식,아무무,1/7/11',
          ],
        },
      },
      {
        date: '2020-10-05',
        result: '3승 0패 A팀 승리',
        teamA: {
          first: [
            '어쩔응슈,카밀,4/4/1',
            '케이윌 꽃이핀다,케인,11/1/16',
            '나밟꿈,갈리오,1/0/16, 29킬 중 17킬 관여',
            '4송합니다,카이사, 10/1/10',
            '순줌,레오나,3/1/17',
          ],
          second: [
            '어쩔응슈,그레이브즈,9/5/5',
            '케이윌 꽃이핀다,14/8/5',
            '나밟꿈,갈리오,1/3/19 37킬중 20킬 관여',
            '4송합니다,미스포춘,8/6/15',
            '순줌,카르마,5/3/14',
          ],
          third: [
            '어쩔응슈,리븐,5/5/8',
            '케이윌 꽃이핀다,리신,13/4/16',
            '나밟꿈,그라가스,3/4/19 34킬 중 22킬 관여',
            '사미랴,사미라,13/5/9',
            '순줌,블리츠크랭크,0/6/11',
          ],
        },

        teamB: {
          first: [
            '워윅 킴,워윅,5/4/0',
            '95황재훈,쉬바나,0/6/2',
            '하루몽,빅토르,1/6/3 7킬중 4킬 관여',
            '티모야힘내,사미라,1/7/1',
            '꽃승아,아무무,0/6/2',
          ],
          second: [
            '워윅 킴,워윅,3/9/7',
            '95황재훈,람머스,5/6/14',
            '하루몽,베인,7/7/5 25킬중 12킬 관여',
            '티모야힘내,케이틀린,6/8/11',
            '꽃승아,모르가나,4/7/12',
          ],
          third: [
            '워윅 킴,워윅,9/7/4',
            '하루몽,제드,10/8/4',
            '95황재훈,벡스,2/6/5, 23킬 중 7킬관여',
            '티모야힘내,이즈리얼,2/4/6',
            '꽃승아,레오나,0/9/7',
          ],
        },
      },
    ],
  },
};

export default common;
